[package]
name = "platform-bin"
version = "0.1.0"
authors = ["taylor <taylor@teukka.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
markdown = { path = "../libs/markdown" }
logging = { path = "../libs/logging" }
www = { path = "../libs/www" }
threadpool = "1.8.1"
urlencoding = "1.1.1"
tokio = { version = "1", features = ["full"] }
toml = "0.5.8"
directories = "3.0.1"
serde_derive = "1.0.125"
serde = "1.0.125"
shellexpand = "2.1.0"

