[package]
name = "tendril"
version = "0.0.8"
authors = ["taylor <taylor@teukka.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logging = { path = "../libs/logging" }
build = { path = "../libs/build" }
tasks = { path = "../libs/tasks" }
www = { path = "../libs/www" }
tokio = { version = "1", features = ["full"] }
