[package]
name = "tendril"
version = "0.1.23"
authors = ["taylor <taylor@teukka.tech>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
build = { path = "../libs/build" }
futures = "0.3.21"
logging = { path = "../libs/logging" }
markdown = { path = "../libs/markdown" }
persistance = { path = "../libs/persistance" }
search-engine = { path = "../libs/search-engine" }
tasks = { path = "../libs/tasks" }
tokio = { version = "1.17.0", features = ["fs", "macros", "rt-multi-thread"] }
www = { path = "../libs/www" }
