name: Build And Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Run tests
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      matrix:
        os:
          - runs-on: ubuntu-latest
            nextest-platform: linux
        rust-version: [stable]
    steps:
      - name: Install latest nextest release
        # The following line is required for Windows compatibility
        shell: bash
        run: |
          curl -LsSf https://get.nexte.st/latest/${{ matrix.os.nextest-platform }} | \
            tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
      - name: Test with latest nextest release
        run: |
          cargo nextest run
